-- Creates function SafeDiv that divides two numbers
DROP FUNCTION IF EXISTS SafeDiv;

DELIMITER //
CREATE FUNCTION SafeDiv (a FLOAT, b FLOAT)
RETURNS FLOAT
DETERMINISTIC
NO SQL
BEGIN
	IF (b = 0) THEN
		RETURN 0;
	ELSE
		RETURN a / b;
	END IF;
END//
DELIMITER ;
